version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Persist SQLite database
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/validate"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional PostgreSQL for future scaling
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ontoseed
      POSTGRES_USER: ontoseed
      POSTGRES_PASSWORD: changeme123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: ontoseed-network