name: Auto Project Management

on:
  issues:
    types: [opened, assigned, closed, reopened]
  pull_request:
    types: [opened, closed, reopened, converted_to_draft, ready_for_review]

jobs:
  manage-project:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to Backlog when opened
        if: github.event.action == 'opened' && github.event.issue
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Savas-us/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: false
          label-operator: AND

      - name: Move issue to Sprint To-Do when assigned
        if: github.event.action == 'assigned' && github.event.issue
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Savas-us/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: false
          label-operator: AND

      - name: Move issue to Done when closed
        if: github.event.action == 'closed' && github.event.issue
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Savas-us/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: false
          label-operator: AND

      - name: Move PR to In Progress when opened
        if: github.event.action == 'opened' && github.event.pull_request
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Savas-us/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: false
          label-operator: AND

      - name: Move PR to Review when ready for review
        if: github.event.action == 'ready_for_review' && github.event.pull_request
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Savas-us/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: false
          label-operator: AND

      - name: Move PR to Done when closed and merged
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Savas-us/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: false
          label-operator: AND